spring:
  application:
    name: banfico-hackathon-backend

  ai:
    ollama:
      base-url: ${SPRING_AI_OLLAMA_BASE_URL:http://localhost:11434}
      chat:
        model: qwen2.5:7b
        options:
          temperature: 0.0

server:
  port: 9091

logging:
  level:
    org:
      springframework:
        ai: DEBUG